// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0ikK4nk9-Fqj2l2Tl-jSR7snlRYWdtzo',
    appId: '1:490733985874:web:0b6feb166934f38b9cff8b',
    messagingSenderId: '490733985874',
    projectId: 'flutterapp-5b272',
    authDomain: 'flutterapp-5b272.firebaseapp.com',
    storageBucket: 'flutterapp-5b272.appspot.com',
    measurementId: 'G-40M00VWGPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn8Z3zjzCN9fX4jIXLQ0JPXcKxPR7hbzE',
    appId: '1:490733985874:android:1fd9dd162d06900c9cff8b',
    messagingSenderId: '490733985874',
    projectId: 'flutterapp-5b272',
    storageBucket: 'flutterapp-5b272.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOXwvS_xVhcTgYDg-POlGEK2fe6jOCxrs',
    appId: '1:490733985874:ios:3438a89c153863919cff8b',
    messagingSenderId: '490733985874',
    projectId: 'flutterapp-5b272',
    storageBucket: 'flutterapp-5b272.appspot.com',
    iosClientId: '490733985874-cddnpsupmlkc4dgt8e3m1iqcn9vncs4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOXwvS_xVhcTgYDg-POlGEK2fe6jOCxrs',
    appId: '1:490733985874:ios:3438a89c153863919cff8b',
    messagingSenderId: '490733985874',
    projectId: 'flutterapp-5b272',
    storageBucket: 'flutterapp-5b272.appspot.com',
    iosClientId: '490733985874-cddnpsupmlkc4dgt8e3m1iqcn9vncs4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileProject1',
  );
}
